name: Hello World

on: 
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Toto
        run: echo "${{ secrets['toTO'] }}"
      - name: Tata
        run: echo "${{ secrets['TAta'] }}"
